#pragma once
#include"Organism.h"
#include"Human.h"
#include"Wolf.h"
#include"Sheep.h"
#include"Fox.h"
#include"Turtle.h"
#include"Antelope.h"
#include"Human.h"
#include"Grass.h"
#include"Milk.h"
#include"Guarana.h"
#include"Berry.h"
#include"Borscht.h"